# !!python/object:argparse.Namespace
_name: graphormer_slim
act_dropout: 0.1
activation_fn: gelu
adam_betas: (0.9, 0.999)
adam_eps: 1.0e-08
all_gather_list_size: 16384
amp: false
amp_batch_retries: 2
amp_init_scale: 128
amp_scale_window: null
apply_graphormer_init: true
arch: graphormer_slim
attention_dropout: 0.1
azureml_logging: false
batch_size: 64
batch_size_valid: 64
best_checkpoint_metric: loss
bf16: false
bpe: null
broadcast_buffers: false
bucket_cap_mb: 25
checkpoint_shard_count: 1
checkpoint_suffix: ''
clip_norm: 5.0
combine_valid_subsets: null
cpu: false
cpu_offload: false
criterion: l1_loss
curriculum: 0
data_buffer_size: 20
dataset_impl: null
dataset_name: zinc
dataset_source: pyg
ddp_backend: legacy_ddp
ddp_comm_hook: none
device_id: 0
disable_validation: false
distributed_backend: nccl
distributed_init_method: null
distributed_no_spawn: false
distributed_num_procs: 1
distributed_port: -1
distributed_rank: 0
distributed_world_size: 1
dropout: 0.0
edge_type: multi_hop
ema_decay: 0.9999
ema_fp32: false
ema_seed_model: null
ema_start_update: 0
ema_update_freq: 1
empty_cache_freq: 0
encoder_attention_heads: 32
encoder_embed_dim: 512
encoder_ffn_embed_dim: 512
encoder_layers: 12
encoder_normalize_before: true
end_learning_rate: 1.0e-09
eos: 2
fast_stat_sync: false
find_unused_parameters: false
finetune_from_model: null
fix_batches_to_gpus: false
fixed_validation_seed: null
force_anneal: null
fp16: true
fp16_adam_stats: false
fp16_init_scale: 128
fp16_no_flatten_grads: false
fp16_scale_tolerance: 0.0
fp16_scale_window: null
fp32_reduce_scatter: false
gen_subset: test
gradient_as_bucket_view: false
grouped_shuffling: false
heartbeat_timeout: -1
ignore_unused_valid_subsets: false
keep_best_checkpoints: -1
keep_interval_updates: -1
keep_interval_updates_pattern: -1
keep_last_epochs: -1
load_checkpoint_on_all_dp_ranks: false
load_pretrained_model_output_layer: false
localsgd_frequency: 3
log_file: null
log_format: null
log_interval: 100
lr:
- 0.0002
lr_scheduler: polynomial_decay
max_epoch: 10000
max_nodes: 128
max_tokens: null
max_tokens_valid: null
max_update: 0
max_valid_steps: null
maximize_best_checkpoint_metric: false
memory_efficient_bf16: false
memory_efficient_fp16: false
min_loss_scale: 0.0001
model_parallel_size: 1
multi_hop_max_dist: 5
no_epoch_checkpoints: false
no_last_checkpoints: false
no_progress_bar: false
no_reshard_after_forward: false
no_save: false
no_save_optimizer_state: false
no_seed_provided: false
no_token_positional_embeddings: false
not_fsdp_flatten_parameters: false
nprocs_per_node: 1
num_atoms: 4608
num_classes: 1
num_edge_dis: 128
num_edges: 1536
num_in_degree: 512
num_out_degree: 512
num_shards: 1
num_spatial: 512
num_workers: 16
on_cpu_convert_precision: false
optimizer: adam
optimizer_overrides: '{}'
pad: 1
patience: -1
pipeline_balance: null
pipeline_checkpoint: never
pipeline_chunks: 0
pipeline_decoder_balance: null
pipeline_decoder_devices: null
pipeline_devices: null
pipeline_encoder_balance: null
pipeline_encoder_devices: null
pipeline_model_parallel: false
plasma_path: /tmp/plasma
power: 1.0
pre_layernorm: false
pretrained_model_name: none
profile: false
quantization_config_path: null
required_batch_size_multiple: 8
required_seq_len_multiple: 1
reset_dataloader: false
reset_logging: false
reset_lr_scheduler: false
reset_meters: false
reset_optimizer: false
restore_file: checkpoint_last.pt
save_dir: ./ckpts
save_interval: 1
save_interval_updates: 0
scoring: bleu
seed: 1
sentence_avg: false
shard_id: 0
share_encoder_input_output_embed: false
simul_type: null
skip_invalid_size_inputs_valid_test: false
skip_remainder_batch: false
slowmo_base_algorithm: localsgd
slowmo_momentum: null
spatial_pos_max: 1024
stop_min_lr: -1.0
stop_time_hours: 0
store_ema: false
suppress_crashes: false
task: graph_prediction
tensorboard_logdir: null
threshold_loss_scale: null
tokenizer: null
total_num_update: '400000'
tpu: false
train_epoch_shuffle: false
train_subset: train
unk: 3
update_epoch_batch_itr: false
update_freq:
- 1
update_ordered_indices_seed: false
use_bmuf: false
use_old_adam: false
use_plasma_view: false
use_sharded_state: false
user_data_dir: ''
user_dir: /sharefs/sharefs-skfeng/Graphormer/graphormer
valid_subset: valid
validate_after_updates: 0
validate_interval: 1
validate_interval_updates: 0
wandb_project: null
warmup_updates: 60000
weight_decay: 0.01
write_checkpoints_asynchronously: false
zero_sharding: none
